/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.accdesign;

import java.awt.CardLayout;
import java.text.DateFormat;
import java.util.Date;


/**
 *
 * @author leong
 */
public class Basic extends javax.swing.JFrame {

    /**
     * Creates new form Basic
     */
    public Basic() {
        initComponents();

    }

    
//    public void clock() { 
//        Timer t = new Timer(0, new ActionListener() {
//                @Override
//                public void actionPerformed(ActionEvent e) { 
//                    
//                    Date date = new Date();
//                    SimpleDataFormat st = new SimpleDateFormat("hh:mm:ss");
//                    
//                    String tt = st.format(dt);
//                }
//                        
//        });
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holderPane = new javax.swing.JPanel();
        homePane = new javax.swing.JPanel();
        baseDisplay = new javax.swing.JLayeredPane();
        jTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        toGo = new javax.swing.JButton();
        addTab = new javax.swing.JButton();
        booking = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        clockIO = new javax.swing.JButton();
        payBill = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        menuPane = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("U&ME RESTAURAUNT POS");
        setBackground(new java.awt.Color(3, 20, 36));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 675));

        holderPane.setPreferredSize(new java.awt.Dimension(1200, 675));
        holderPane.setLayout(new java.awt.CardLayout());

        homePane.setBackground(new java.awt.Color(153, 161, 172));
        homePane.setPreferredSize(new java.awt.Dimension(1200, 675));

        baseDisplay.setBackground(new java.awt.Color(29, 39, 49));
        baseDisplay.setOpaque(true);
        baseDisplay.setPreferredSize(new java.awt.Dimension(696, 675));

        jTime.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jTime.setForeground(new java.awt.Color(255, 255, 255));
        jTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jTime.setText(DateFormat.getTimeInstance(DateFormat.SHORT).format(new Date()));
        jTime.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(DateFormat.getDateInstance(DateFormat.SHORT).format(new Date()));
        jLabel1.setToolTipText("");

        baseDisplay.setLayer(jTime, javax.swing.JLayeredPane.DEFAULT_LAYER);
        baseDisplay.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout baseDisplayLayout = new javax.swing.GroupLayout(baseDisplay);
        baseDisplay.setLayout(baseDisplayLayout);
        baseDisplayLayout.setHorizontalGroup(
            baseDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseDisplayLayout.createSequentialGroup()
                .addContainerGap(360, Short.MAX_VALUE)
                .addGroup(baseDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTime, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39))
        );
        baseDisplayLayout.setVerticalGroup(
            baseDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseDisplayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        toGo.setBackground(new java.awt.Color(73, 100, 146));
        toGo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        toGo.setForeground(new java.awt.Color(255, 255, 255));
        toGo.setText("TO GO");
        toGo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));
        toGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toGoActionPerformed(evt);
            }
        });

        addTab.setBackground(new java.awt.Color(73, 100, 146));
        addTab.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        addTab.setForeground(new java.awt.Color(255, 255, 255));
        addTab.setText("ORDER");
        addTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));
        addTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTabActionPerformed(evt);
            }
        });

        booking.setBackground(new java.awt.Color(73, 100, 146));
        booking.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        booking.setForeground(new java.awt.Color(255, 255, 255));
        booking.setText("BOOKING");
        booking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));
        booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingActionPerformed(evt);
            }
        });

        admin.setBackground(new java.awt.Color(73, 100, 146));
        admin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("ADMIN");
        admin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        clockIO.setBackground(new java.awt.Color(73, 100, 146));
        clockIO.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        clockIO.setForeground(new java.awt.Color(255, 255, 255));
        clockIO.setText("CLOCK I/O");
        clockIO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));

        payBill.setBackground(new java.awt.Color(73, 100, 146));
        payBill.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        payBill.setForeground(new java.awt.Color(255, 255, 255));
        payBill.setText("PAY BILL");
        payBill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));

        menu.setBackground(new java.awt.Color(73, 100, 146));
        menu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("MENU");
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 68, 102), 5));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePaneLayout = new javax.swing.GroupLayout(homePane);
        homePane.setLayout(homePaneLayout);
        homePaneLayout.setHorizontalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePaneLayout.createSequentialGroup()
                .addComponent(baseDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homePaneLayout.createSequentialGroup()
                        .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(payBill, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clockIO, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(booking, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTab, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toGo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        homePaneLayout.setVerticalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toGo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addTab, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payBill, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(booking, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockIO, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addComponent(baseDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        holderPane.add(homePane, "homePane");

        menuPane.setBackground(new java.awt.Color(29, 39, 49));

        jSplitPane2.setBackground(new java.awt.Color(68, 91, 115));
        jSplitPane2.setDividerLocation(505);
        jSplitPane2.setDividerSize(0);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 91, 115), 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jSplitPane2.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel2);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout menuPaneLayout = new javax.swing.GroupLayout(menuPane);
        menuPane.setLayout(menuPaneLayout);
        menuPaneLayout.setHorizontalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
            .addGroup(menuPaneLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuPaneLayout.setVerticalGroup(
            menuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPaneLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        holderPane.add(menuPane, "menuPane");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(holderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(holderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toGoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toGoActionPerformed

    private void addTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTabActionPerformed

    private void bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)holderPane.getLayout();
        card.show(holderPane, "menuPane");
    }//GEN-LAST:event_menuActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Basic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTab;
    private javax.swing.JButton admin;
    private javax.swing.JLayeredPane baseDisplay;
    private javax.swing.JButton booking;
    private javax.swing.JButton clockIO;
    private javax.swing.JPanel holderPane;
    private javax.swing.JPanel homePane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel jTime;
    private javax.swing.JButton menu;
    private javax.swing.JPanel menuPane;
    private javax.swing.JButton payBill;
    private javax.swing.JButton toGo;
    // End of variables declaration//GEN-END:variables
}
